### ISSUE TITLE
Mod compatibility: BCLib and Overlay tweaks

### ISSUE THREAD

**Issue by Chief0609** [MicrocontrollersDev/OverlayTweaks#23] opened 2024-03-15 00:17 UTC
I was in the process of debugging a mod pack and Mixin Conflict Helper noticed a discrepancy between BCLib (newest and older versions) and OverlayTweaks (newest and older versions). It does not tell me what is wrong just that it is

Fabric Loader: 15.7
Minecraft Version: 1.20.1
Mods in question: BCLib, Overlay Tweaks

**Comment by MicrocontrollersDev** [comment] 2024-03-15 08:12
can confirm, issue is with anvil screen opacity

https://github.com/quiqueck/BCLib/blob/3b23118a28bbea0363e25378aab38cbff45f9683/src/main/java/org/betterx/bclib/mixin/client/AnvilScreenMixin.java#L72

https://github.com/MicrocontrollersDev/OverlayTweaks/blob/1.20.4/src/main/java/dev/microcontrollers/overlaytweaks/mixin/screenopacity/AnvilScreenMixin.java

i think just changing mixin priority is enough to fix this, will look further into this tomorrow

**Comment by MicrocontrollersDev** [comment] 2024-03-16 01:14
should be fixed in 1.7.4 please reopen issue if not

**Closed by MicrocontrollersDev** 2024-03-16 01:14 UTC
Labels: bug

**Comment by Chief0609** [comment] 2024-03-17 04:37
so fixing this kinda broke everything, texturepacks disable everytime I launch the game, and I went to make a world and the game crashed

**Comment by MicrocontrollersDev** [comment] 2024-03-17 04:41
that makes no sense :sob: all i did was change mixin priority so BCLib applies first, then my mod. I haven't changed any actual code

**Comment by MicrocontrollersDev** [comment] 2024-03-17 04:45
I am unable to reproduce. Created a world just fine with BCLib and my texture packs stayed loaded on reconnect

**Comment by Chief0609** [comment] 2024-03-17 16:12
> I am unable to reproduce. Created a world just fine with BCLib and my texture packs stayed loaded on reconnect

Yeah, tried it on my vanilla client, worked fine
might be a different mod incompatability, it is a modpack,  going through it rn, ill update you on what mod it might be
